In [2]:
import numpy as np
np.__version__

'1.26.3'

#### numpy

- 일반적인 배열 + 배열 연산자를 쓰면 배열1배열2 형태로 출력됨
- numpy를 이용하면 배열 안의 요소들의 연산을 쉽게 할 수 있음

In [3]:
num1 = [1, 2, 3, 4]
num2 = [3, 4, 5, 6]
num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [4]:
arr1 = np.array(num1)
arr1

array([1, 2, 3, 4])

In [5]:
arr2 = np.array(num2)
arr2

array([3, 4, 5, 6])

In [6]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
#배열 개수가 다르면 에러가 나옴

[ 4  6  8 10]
[-2 -2 -2 -2]
[ 3  8 15 24]
[0.33333333 0.5        0.6        0.66666667]


In [7]:
np.array([0.5, 1, 0.01, 8]).dtype # float 비트단위 연산으로 출력됨

dtype('float64')

In [8]:
data1 = [0, 1, 2, 3]
a1 = np.array(data1)
a1

array([0, 1, 2, 3])

In [9]:
print(a1.dtype) #int32

int32


In [10]:
print(np.arange(3, 10))
print(np.arange(1, 10, 2))
print(np.arange(10)) #시작인덱스가 0이면 생략가능

[3 4 5 6 7 8 9]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


- np.arange(12) #1차원 배열
- np.arange(12).reshape(a, b) #2차원 배열
- np.arange(12).reshape(c, d, e) #3차원 배열
- reshape를 통해서 다른 차원으로 배열로 변경할 수 있다.
- 이때 a * b = c * d * e = 12. 크기는 유지 되어야 한다.
- 만약 다르면 에러가 발생함

In [11]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
print(np.arange(12))
print("")
print(np.arange(12).reshape(3, 4))
print("")
print(np.arange(12).reshape(2, 3, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [13]:
b1 = np.arange(27).reshape(3, 3, 3)
b1.shape #shape를 통해서 배열의 차원을 확인할 수 있다.

(3, 3, 3)

In [14]:
b2 = np.arange(27)
b2.shape #1차원 배열은 (27,) 로 출력됨

(27,)

#### np.linspace()
- np.linspapce(시작값, 끝값, 배열의 길이)
- 배열의 길이 = 추출할 값의 개수
- np.linspace(0, 10, 5) #0이상 10 이하의 균일한 간격의 실수 5개의 배열을 생성한다.
- np.arange(0, 11, 2.5) #0이상 11 미만의 2.5 간격의 수의 배열을 생성한다.
- 차이를 알아두자

In [15]:
np.arange(0, 11, 2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
print(np.arange(0, 11, 2.5))
print(np.linspace(0, 10, 5))
#출력 모양은 같지만 실제로는 다름

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]


In [18]:
np.linspace(0, np.pi, 10) #0이상 3.14...인 파이값 사이에 10개의 값을 생성한다.

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [19]:
#초기화 함수
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
np.zeros((2, 10)) #2행 10열의 배열을 만들고 모든 요소를 0으로 초기화.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [22]:
#단위 행렬 함수
arrI = np.eye(3)
arrI

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arrI.shape

(3, 3)

In [24]:
#문자열 데이터 배열
np.array(["1.5", "0.25"]) #dtype='<U4'

array(['1.5', '0.25'], dtype='<U4')

In [25]:
#문자열 데이터를 연산을 하기 위해서는 정수나 실수 형태로 변환해야 한다.
arr = np.array(["1.5", "0.25", "5"])
numArr = arr.astype(float)
numArr

array([1.5 , 0.25, 5.  ])

In [26]:
numArr + np.array([1, 2, 3])

array([2.5 , 2.25, 8.  ])

In [27]:
intArr = numArr.astype(int)
floatArr = numArr.astype(float)
print(intArr) #소수점 아래를 버림. 지양할 타입
print(floatArr) #온전한 형태로 출력됨 

[1 0 5]
[1.5  0.25 5.  ]


#### 난수 무작위 추출
- np.random.rand(a, b, c): 0부터 1사이의 실수를 랜덤으로 추출 후 배열. 1, 2, 3차원 모두 가능함
- np.random.randint(c, d, n): c와 d 사이의 n개의 정수를 랜덤으로 추출 후 배열. 이때 d는 포함 안 됨
- 이때 n에 정수 대신 (e, f) 같은 방식으로 tuple을 넣어 배열을 만들 수 있다.

In [33]:
np.random.rand(2)

array([0.48225291, 0.81143557])

In [36]:
np.random.rand(2, 3, 4)

array([[[0.38110494, 0.76155746, 0.77123282, 0.47604901],
        [0.98141942, 0.6367894 , 0.06568786, 0.45546524],
        [0.24582951, 0.67112251, 0.38559672, 0.73242494]],

       [[0.62764934, 0.05326718, 0.68755716, 0.11398032],
        [0.3545683 , 0.51322357, 0.60784578, 0.97071652],
        [0.01642937, 0.1755338 , 0.6269507 , 0.36912149]]])

In [37]:
np.random.randint(1, 100, 5)

array([38,  5, 14, 56, 53])

In [40]:
np.random.randint(1, 100, (2, 3, 4))

array([[[11, 70, 82, 38],
        [21, 13, 37, 52],
        [85, 48, 27, 74]],

       [[99, 93, 23, 90],
        [81,  9, 72, 73],
        [28, 35, 10,  3]]])

#### 배열의 연산
- 합, 평균, 표준편차, 분산, 최솟값, 최댓값, 누적합, 누적곱 메서드가 존재한다
- 기술통계량(Descipttive Statistic): 현재 데이터 상태를 표현하는 통계량

In [43]:
arr3 = np.arange(5)
print(f'arr3는 {arr3}')
print(arr3.sum())
print(arr3.mean()) #평균
print(arr3.std()) #표준편차
print(arr3.var()) #분산

arr3는 [0 1 2 3 4]
10
2.0
1.4142135623730951
2.0


#### 행렬연산

In [44]:
A = np.array([2, 3, 4, 5]).reshape(2, 2)
B = np.array([6, 7, 8, 9]).reshape(2, 2)
print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [47]:
# 행렬의 곱셈
A.dot(B)

array([[36, 41],
       [64, 73]])

In [50]:
# 배열의 곱셈 기능도 존재함
a = np.array([2, 3, 4, 5])
b = np.array([6, 7, 8, 9])
a.dot(b)

110

In [52]:
#전치행렬 -> 행렬의 행과 열을 바꾼 행랼
A.transpose()

array([[2, 4],
       [3, 5]])

In [55]:
#역행렬
np.linalg.inv(A)

array([[-2.5,  1.5],
       [ 2. , -1. ]])