In [1]:
import numpy as np
np.__version__

'1.26.3'

#### numpy

- 일반적인 배열 + 배열 연산자를 쓰면 배열1배열2 형태로 출력됨
- numpy를 이용하면 배열 안의 요소들의 연산을 쉽게 할 수 있음

In [2]:
num1 = [1, 2, 3, 4]
num2 = [3, 4, 5, 6]
num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [3]:
arr1 = np.array(num1)
arr1

array([1, 2, 3, 4])

In [4]:
arr2 = np.array(num2)
arr2

array([3, 4, 5, 6])

In [5]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
#배열 개수가 다르면 에러가 나옴

[ 4  6  8 10]
[-2 -2 -2 -2]
[ 3  8 15 24]
[0.33333333 0.5        0.6        0.66666667]


In [6]:
np.array([0.5, 1, 0.01, 8]).dtype # float 비트단위 연산으로 출력됨

dtype('float64')

In [7]:
data1 = [0, 1, 2, 3]
a1 = np.array(data1)
a1

array([0, 1, 2, 3])

In [8]:
print(a1.dtype) #int32

int32


In [9]:
print(np.arange(3, 10))
print(np.arange(1, 10, 2))
print(np.arange(10)) #시작인덱스가 0이면 생략가능

[3 4 5 6 7 8 9]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


- np.arange(12) #1차원 배열
- np.arange(12).reshape(a, b) #2차원 배열
- np.arange(12).reshape(c, d, e) #3차원 배열
- reshape를 통해서 다른 차원으로 배열로 변경할 수 있다.
- 이때 a * b = c * d * e = 12. 크기는 유지 되어야 한다.
- 만약 다르면 에러가 발생함

In [10]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
print(np.arange(12))
print("")
print(np.arange(12).reshape(3, 4))
print("")
print(np.arange(12).reshape(2, 3, 2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [12]:
b1 = np.arange(27).reshape(3, 3, 3)
b1.shape #shape를 통해서 배열의 차원을 확인할 수 있다.

(3, 3, 3)

In [13]:
b2 = np.arange(27)
b2.shape #1차원 배열은 (27,) 로 출력됨

(27,)

#### np.linspace()
- np.linspapce(시작값, 끝값, 배열의 길이)
- 배열의 길이 = 추출할 값의 개수
- np.linspace(0, 10, 5) #0이상 10 이하의 균일한 간격의 실수 5개의 배열을 생성한다.
- np.arange(0, 11, 2.5) #0이상 11 미만의 2.5 간격의 수의 배열을 생성한다.
- 차이를 알아두자

In [14]:
np.arange(0, 11, 2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
print(np.arange(0, 11, 2.5))
print(np.linspace(0, 10, 5))
#출력 모양은 같지만 실제로는 다름

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]


In [17]:
np.linspace(0, np.pi, 10) #0이상 3.14...인 파이값 사이에 10개의 값을 생성한다.

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [18]:
#초기화 함수
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
np.zeros((2, 10)) #2행 10열의 배열을 만들고 모든 요소를 0으로 초기화.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [21]:
#단위 행렬 함수
arrI = np.eye(3)
arrI

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arrI.shape

(3, 3)

In [23]:
#문자열 데이터 배열
np.array(["1.5", "0.25"]) #dtype='<U4'

array(['1.5', '0.25'], dtype='<U4')

In [24]:
#문자열 데이터를 연산을 하기 위해서는 정수나 실수 형태로 변환해야 한다.
arr = np.array(["1.5", "0.25", "5"])
numArr = arr.astype(float)
numArr

array([1.5 , 0.25, 5.  ])

In [25]:
numArr + np.array([1, 2, 3])

array([2.5 , 2.25, 8.  ])

In [26]:
intArr = numArr.astype(int)
floatArr = numArr.astype(float)
print(intArr) #소수점 아래를 버림. 지양할 타입
print(floatArr) #온전한 형태로 출력됨 

[1 0 5]
[1.5  0.25 5.  ]


#### 난수 무작위 추출
- np.random.rand(a, b, c): 0부터 1사이의 실수를 랜덤으로 추출 후 배열. 1, 2, 3차원 모두 가능함
- np.random.randint(c, d, n): c와 d 사이의 n개의 정수를 랜덤으로 추출 후 배열. 이때 d는 포함 안 됨
- 이때 n에 정수 대신 (e, f) 같은 방식으로 tuple을 넣어 배열을 만들 수 있다.

In [27]:
np.random.rand(2)

array([0.19517298, 0.74078605])

In [28]:
np.random.rand(2, 3, 4)

array([[[0.05838049, 0.77316909, 0.43440915, 0.79715024],
        [0.21047321, 0.63574471, 0.75975147, 0.9792842 ],
        [0.39140929, 0.87225704, 0.94180161, 0.18698488]],

       [[0.58026044, 0.37524648, 0.07291529, 0.58106713],
        [0.8274608 , 0.71057556, 0.38917515, 0.42376158],
        [0.57083032, 0.25009017, 0.75198329, 0.21797765]]])

In [29]:
np.random.randint(1, 100, 5)

array([40, 86, 65, 28, 33])

In [30]:
np.random.randint(1, 100, (2, 3, 4))

array([[[71, 83, 87, 39],
        [11, 60, 17, 25],
        [59, 17, 96, 51]],

       [[93, 71, 46, 54],
        [26, 50, 47, 55],
        [21, 27, 35, 16]]])

#### 배열의 연산
- 합, 평균, 표준편차, 분산, 최솟값, 최댓값, 누적합, 누적곱 메서드가 존재한다
- 기술통계량(Descipttive Statistic): 현재 데이터 상태를 표현하는 통계량

In [31]:
arr3 = np.arange(5)
print(f'arr3는 {arr3}')
print(arr3.sum())
print(arr3.mean()) #평균
print(arr3.std()) #표준편차
print(arr3.var()) #분산

arr3는 [0 1 2 3 4]
10
2.0
1.4142135623730951
2.0


#### 행렬연산

In [32]:
A = np.array([2, 3, 4, 5]).reshape(2, 2)
B = np.array([6, 7, 8, 9]).reshape(2, 2)
print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [33]:
# 행렬의 곱셈
A.dot(B)

array([[36, 41],
       [64, 73]])

In [34]:
# 배열의 곱셈 기능도 존재함
a = np.array([2, 3, 4, 5])
b = np.array([6, 7, 8, 9])
a.dot(b)

110

In [35]:
#전치행렬 -> 행렬의 행과 열을 바꾼 행랼
A.transpose()

array([[2, 4],
       [3, 5]])

In [36]:
#역행렬
np.linalg.inv(A)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

#### 배열의 인덱싱과 슬라이싱

- 파이썬 시퀀스 자료형의 인덱싱과 슬라이싱과 유사함

In [43]:
a1 = np.array([0, 1, 2, 3, 40, 5])

print(a1[0])
print(a1[-1])

0
5


In [44]:
#리스트를 통한 추출
a1[[0, 2, 4]]

array([ 0,  2, 40])

In [48]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

2차원 배열의 인덱스 위치는 다음과 같다
- 배열[열, 행]
<br>
(0, 0) (0, 1) (0, 2)<br>
(1, 0) (1, 1) (1, 2)<br>
(2, 0) (2, 1) (2, 2)<br>

In [49]:
print(a2[0, 1])
print(a2[1, 2])
print(a2[2, 1])

20
60
80


In [50]:
#배열값 업데이트
a2[0, 2] = 60
a2

array([[10, 20, 60],
       [40, 50, 60],
       [70, 80, 90]])

In [52]:
#행 하나 전체 출력
a2[1]

array([40, 50, 60])

In [55]:
#행 전체 업데이트
a2[1] = np.array([1, 2, 3]) 
a2

array([[10, 20, 60],
       [ 1,  2,  3],
       [70, 80, 90]])

In [64]:
#2차원 배열의 행과 열 위치를 지정해서 원소 추출
a2 = np.arange(10, 100, 10).reshape(3, 3)
print(a2)
"""
(0, 0) (0, 1) (0, 2)
(0, 0) (1, 1) (1, 2)
(2, 0) (2, 1) (2, 2)
"""

[[10 20 30]
 [40 50 60]
 [70 80 90]]


'\n(0, 0) (0, 1) (0, 2)\n\n(1, 0) (1, 1) (1, 2)\n\n(2, 0) (2, 1) (2, 2)\n\n'

In [78]:
a2[[0,2],[0,1]]
# [(0, 0) 위치의 원소, (2,1)위치의 원소] 를 생성
# 배열[열, 행]

array([10, 80])

In [83]:
b1 = np.arange(0, 11)
b1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
b1[1:4]

array([1, 2, 3])

In [88]:
b1[0:11:2] #0이상 11미만, 2간격

array([ 0,  2,  4,  6,  8, 10])

In [92]:
b1[1:4] = np.array([10, 20, 30])
b1

array([ 0, 10, 20, 30,  4,  5,  6,  7,  8,  9, 10])

In [96]:
b1[4:11] = 80
b1

array([ 0, 10, 20, 30, 80, 80, 80, 80, 80, 80, 80])

In [100]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [104]:
b2[0:2, 1:3] #열: 0부터 1까지, 행: 1부터 2까지

array([[20, 30],
       [50, 60]])

In [107]:
list1 = [1, 2, 3, ["a","b"]]
list1[3][1] #중첩 리스트의 3번째 인덱스의 1번째 인덱스

'b'

In [109]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2
print(b2[1])
print(b2[1][0:2]) #b2의 1인덱스 행의 0부터 2미만 행 원소들

[40 50 60]
[40 50]


#### 배열 조건문

In [69]:
a3 = np.array([0, 1, 2, 3, 4, 5, 6])
a3

array([0, 1, 2, 3, 4, 5, 6])

In [74]:
a3 > 3

array([False, False, False, False,  True,  True,  True])

In [75]:
a3[a3 > 3] #True 값만 추출

array([4, 5, 6])

In [76]:
a3 % 2 == 0 #s나머지가 0인 원소

array([ True, False,  True, False,  True, False,  True])

In [77]:
a3[a3 % 2 == 0]

array([0, 2, 4, 6])

#### numpy의 조건문
- np.where(조건, x, y) : 단일 조건문. 조건에 참인 경우 x, 조건에 거짓인 경우 y를 반환한다.
- np.select(조건리스트, 결과리스트, 디폴트값): 다중 조건문. 조건리스트와 결과리스트를 불러오고, 전부 false인 경우 디폴트를 반환한다.

In [111]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.where(arr1 < 5, arr1, arr1*10) #5보다 작으면 arr1 그대로, 크거나 같으면 10을 곱한다.

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [116]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
comdList = [arr2 > 5, arr2 == 1]
choiceList = [arr2*10, 0]

np.select(comdList, choiceList, default = arr2)

array([ 0,  0,  2,  3,  4,  5, 60, 70, 80, 90])